package sant1ago.dev.suprim.annotation.type;

/**
 * Primary key generation strategies.
 *
 * <pre>{@code
 * @Id(strategy = GenerationType.UUID_V7)
 * private String id;
 *
 * @Id(strategy = GenerationType.IDENTITY)
 * private Long id;
 * }</pre>
 */
public enum GenerationType {

    /**
     * No automatic generation - value must be set manually.
     */
    NONE,

    /**
     * Database auto-increment (PostgreSQL SERIAL/IDENTITY, MySQL AUTO_INCREMENT).
     */
    IDENTITY,

    /**
     * Database sequence (PostgreSQL SEQUENCE).
     * Use @Id(sequence = "seq_name") to specify sequence name.
     */
    SEQUENCE,

    /**
     * Standard UUID (v4 - random).
     * Application generates UUID before insert.
     */
    UUID_V4,

    /**
     * Time-ordered UUID (v7).
     * Sortable, better for database indexing.
     * Application generates UUID v7 before insert.
     */
    UUID_V7,

    /**
     * Database-generated UUID.
     * PostgreSQL: gen_random_uuid()
     */
    UUID_DB;

    /**
     * Checks if this strategy is NONE.
     *
     * @return true if no generation strategy
     */
    public boolean isNone() {
        return this == NONE;
    }

    /**
     * Checks if this strategy generates UUIDs.
     *
     * @return true if UUID-based strategy
     */
    public boolean isUuid() {
        return this == UUID_V4 || this == UUID_V7 || this == UUID_DB;
    }

    /**
     * Checks if ID is generated by application.
     *
     * @return true if application generates the ID
     */
    public boolean isApplicationGenerated() {
        return this == UUID_V4 || this == UUID_V7;
    }

    /**
     * Checks if ID is generated by database.
     *
     * @return true if database generates the ID
     */
    public boolean isDatabaseGenerated() {
        return this == IDENTITY || this == SEQUENCE || this == UUID_DB;
    }
}
